# Generated by Django 3.2.3 on 2021-07-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_opened',
            field=models.CharField(choices=[('공개', '공개'), ('비공개', '비공개')], default='공개', max_length=10),
        ),
    ]
