# Generated by Django 3.2.3 on 2021-07-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_is_opened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'user_profile'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
    ]
