# Generated by Django 3.2.3 on 2021-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hospital',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
