# Generated by Django 3.2.3 on 2021-07-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_hospital'),
        ('reviews', '0002_review_writer'),
    ]

    operations = [
    ]
