# Generated by Django 3.2 on 2021-07-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], max_length=5, null=True),
        ),
    ]
