# Generated by Django 3.2.4 on 2021-08-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
